- hosts: localhost
  vars:
      ad_user: Your_user_Id
      password: "Your_Password"
      subscription_id: Your_subscription_Id
  tasks:
    - name: Get facts for one resource group
      azure_rm_resourcegroup_facts:
          ad_user: '{{ ad_user }}'
          password: '{{ password }}'
          subscription_id: '{{ subscription_id }}'
      register: result

    - debug:
        var: result

    - name: Create Azure Deploy
      azure_rm_deployment:
          ad_user: '{{ ad_user }}'
          password: '{{ password }}'
          subscription_id: '{{ subscription_id }}'
          #state: present
          template_link: 'https://raw.githubusercontent.com/Click2Cloud/developer-immersion-data/master/labs/sp-gda/gdaexpericence1/story_a_gda_using_cosmosdb/devops/template.json'
          parameters_link: 'https://raw.githubusercontent.com/Click2Cloud/developer-immersion-data/master/labs/sp-gda/gdaexpericence1/story_a_gda_using_cosmosdb/devops/parameters.json'
          resource_group_name: '{{ result.ansible_facts.azure_resourcegroups[0].name }}'
          location: "southcentralus"
